name: PlayerGraves
version: 0.1
author: Mik_C
main: es.mcers.Mik_C.PlayerGraves.PlayerGraves

commands:
  graves:
    description: "Indica la ubicación de tus puntos de muerte en los últimos 30 minutos."
    usage: "/graves"